config/routes.rb
PhotoOverflow::Application.routes.draw do
  root :to => "questions#index"

  resources :users

  resources :questions do
    resources :answers 
  end
  
  resources :questions, only: [] do
    resources :comments
  end

  resources :votes
  
  resources :answers, only: [] do
    resources :comments
  end

  get '/ask' => 'questions#ask_question', as: :ask_question

  get '/login'   => 'sessions#new'
  post '/login'  => 'sessions#create'
  get '/logout'  => 'sessions#destroy'
  get '/signup'  => 'users#new'
  post '/signup' => 'users#create'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include VotableHelper
  attr_accessible :content, :file, :path, :user_id, :question_id
  has_many :votes, as: :votable
  has_many :comments, as: :commentable
  belongs_to :user
  belongs_to :question

  mount_uploader :file, PhotoUploader

  def self.submit_new_answer(params, question, current_user_id)
    answer = question.answers.build(
      params[:answer],
      question_id: question.id)
      answer.user_id = current_user_id
    answer.save ? answer : false
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include VotableHelper
  attr_accessible :user_id, :content, :commentable_id, :commentable_type
  has_many :votes, as: :votable
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  include VotableHelper
  attr_accessible :file, :title, :content, :path, :user_id
  has_many :votes, as: :votable
  has_many :comments, as: :commentable
  has_many :tagclouds
  has_many :tags, through: :tagclouds
  belongs_to :user
  has_many :answers

  mount_uploader :file, PhotoUploader
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :tagclouds
  has_many :questions, through: :tagclouds
end

app/models/tagcloud.rb
class TagCloud < ActiveRecord::Base
  belongs_to :question
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :email
  has_many :questions
  has_many :answers
  has_many :comments
  has_many :votes

  has_secure_password

  validates_uniqueness_of :email, :username
  validates :email, :username, :password, presence: true
  validates :email, format: { with: /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ }

  def to_s
    "#{username}"
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :votable, polymorphic: true
  belongs_to :user
  attr_accessible :direction, :user_id, :votable_id, :votable_type
  validates_uniqueness_of :votable_id, scope: [:user_id]
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answers = Answer.order("created_at DESC")
  end

  def new
    @answer = Answer.new
  end

  def create
    if current_user
      question = Question.find(params[:answer][:question_id])
        if Answer.create(params[:answer].merge(:user_id => current_user.id))
          redirect_to question
        else
          render question
        end
      else
        redirect_to signup_path
    end
  end

  def show
    @question = Question.find(params[:answer][:question_id])
    @question_answers = Answer.find_all_by_question_id(@question.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :current_user

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @commentable = find_commentable
    @comments = @commentable.comments
  end

  def create
    if current_user
      @commentable = find_commentable
      @comment = @commentable.comments.build(params[:comment])
      @comment.user_id = current_user.id
      if @comment.save
        flash[:notice] = "Successfully created comment"
        redirect_to :back
      else
        render :action => 'new'
      end
    else
      flash[:notice] = "Sign up to add a comment"
      redirect_to '/signup'
    end
  end

# private

  def find_commentable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
  end

  def index
    @questions = Question.all
  end

  def create
    p params.inspect
    Question.create(:file => params[:file], :title => params[:title], :content =>params[:content], :user_id => current_user.id)
    redirect_to questions_path
  end

  def show
    @answer = Answer.new
    @question = Question.find(params[:id])
    @question_answers = @question.answers
  end

  def ask_question
    if current_user
      redirect_to new_question_path
    else
      redirect_to '/login'
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_username(params[:username])
    if @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now.alert = "Invalid email or password"
      render login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def profile_questions
    if current_user
      @questions = Question.find_all_by_user_id(current_user.id)
    else
      redirect :root
    end
  end

  def profile_answers
    if current_user
      @answers = Answer.find_all_by_user_id(current_user.id)
    else
      redirect :root
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user
      redirect_to user_path(current_user)
    else
      render new_user_path
    end
  end

  def show
    if current_user
      @questions = Question.find_all_by_user_id(current_user.id)
      @myanswers = Answer.find_all_by_user_id(current_user.id)
    else
      redirect :root
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    if current_user
      vote = Vote.create(
        votable_id: params[:votable_id],
        votable_type: params[:votable_type],
        direction: params[:direction], 
        user_id: current_user.id)

      votes_count = vote.votable.votes_count
      render json: { votes_count: votes_count }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/votable_helper.rb
module VotableHelper
  def votes_count
    directions = votes.map(&:direction)
    if directions.empty?
      0
    else
      directions.reduce(&:+) - directions.count(&:zero?)
    end
  end
end

app/views/answers/_answer.html.erb
<div class="first_line_all_answers"></div>
  <div class="answer_upload">
  <div class="answer"><span class="answer-vote" id='voting-panel'>
    <%= render partial: 'shared/voting', locals: { votable: answer } %>
  </span>  <img src="<%= answer.path || answer.file  %>"> <%= answer.content %> 
  <div class="answer-username">Answer by: <%= answer.user.username %></div></div>
</div>

<% answer.comments.each do |comment| %>
  <%= render partial: 'comments/comment', locals: { comment: comment } %>
<% end %>

<%= render partial: 'comments/new', locals: { commentable: answer } %>

app/views/answers/_new.html.erb
<div class="answer-form">
<div class="answer-form-intro">Add your answer and upload a photo to go with it. </div>
<%= form_for @answer, :multipart => true, url: question_answers_path(@question) do |f| %>
  <%= f.file_field :file %>
  <%= f.hidden_field :question_id, value: @question.id %>
  <p><%= f.text_area :content, rows: 2 , cols: 35, placeholder: 'Impart your wisdom. Be kind.'  %></p>
  <p><%= f.submit "Submit" %></p>
<% end %>
</div>

app/views/answers/_show.html.erb
<div class="first_line_all_answers"></div>
  <!-- <div class="answer_upload"> -->
  <div class="answer">
  	<table>
  		<tr>
  			<td class="answer-vote"></td>
        <td class="answer-text">
        	<img src="<%= answer.path || answer.file %>"></td>
      </tr>
      <tr>
	      <td class="answer-vote">
	      	<span id='voting-panel'>
	          <%= render partial: 'shared/voting', locals: { votable: answer } %>
	        </span>
	      </td>  	
	      <td>
  	       <%=answer.content %> <span class="answer-username">&ndash;<%= answer.user.username %></span>
        </td>
      <tr>
    	<tr>
    		<td class="answer-vote"></td>
    		<td class="answer-text comment-on-answer">
    			<% answer.comments.each do |comment| %>
    			  <%= render partial: 'comments/comment', locals: { comment: comment } %>
    			<% end %>
    			<%= render partial: 'comments/new', locals: { commentable: answer } %>
    		</td>
    	</tr>
    </table>
  <div>
</div>

app/views/answers/index.html.erb
<div class="answers">
  <%= render @question_answers %>
</div>

app/views/comments/_comment.html.erb
<div class="comment">
  <%= comment.content %>
  <span class="username-comment"> &ndash;<%= comment.user.username %></span>
</div>

app/views/comments/_new.html.erb
<div class="comment_form">
  <%= form_for [commentable, Comment.new] do |f| %>
    <%= f.text_field :content, placeholder: "Add comment for #{commentable.class} here." %>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoOverflow</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
	 <link href='http://fonts.googleapis.com/css?family=Asap:400,400italic' rel='stylesheet' type='text/css'>
	 <link href='http://fonts.googleapis.com/css?family=Quicksand:300,400,700' rel='stylesheet' type='text/css'>
	 <link href="http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- Header -->
	<div class="container">
	    <div class="header row">
	        <div class="span12">
	            <div class="navbar">
	                <div class="navbar-inner">
	                    <h1>
	                        <%= link_to "PhotoOverflow", root_path %>
	                    </h1>
	                    <div class="nav-collapse collapse">
	                        <ul class="nav pull-right">
	                            <li>
	                                <%= link_to root_path do %>
	                                <i class="icon-home"></i><br /><span class="nav-text">Home</span>
	                                <% end %>
	                            </li>
	                            <li>
	                                <%= link_to ask_question_path  do %>
	                                <i class="icon-question-sign"></i><br /><span class="nav-text">Ask a question</span>
	                                  <% end %>
	                            </li>
			                        <li>
	                                <%= render 'shared/navbar_username' %>
	                            </li>
	                            <li>
	                            	  <%= render 'shared/navbar_logout' %> 
	                            </li>
	                        </ul>
	                    </div>
	                </div>
	            </div>
	        </div>
	    </div>
	</div>
<div class="presentation container">
<%= yield %>
</div>
</body>
</html>

app/views/layouts/new-photo.html.erb
<div>
  <%= form_tag({ :action => :create, :controller => :photos }, :multipart => true) do %>
    <%= text_field_tag :title, placeholder: "enter title" %>
    <%= file_field_tag :file %>
    <%= submit_tag("Upload") %>
  <% end %>
</div>

app/views/questions/_question.html.erb
<li class="span3">
    <div class="work">
        <span class="title">
          <%= link_to question.title, question_path(question.id) %>
        </span>
        <div class="title_username"> Asked by: <%= question.user.username %></div>
        <div class="photo_upload">
          <%= link_to question_path(question.id) do %>
          <img src="<%= question.path || question.file %>">
          <% end %>
        </div>
    </div>
</li>

app/views/questions/index.html.erb
<div class="portfolio portfolio-page container">
    <div class="row">
        <ul class="portfolio-img">
					<div class="questions">
  				<%= render @questions.reverse %>
					</div>
        </ul>
    </div>
</div>

app/views/questions/new.html.erb
<div class="ask-container">
    <div class="question_form_intro">Do you have a question about a photograph? <br/>Ask it here and get feedback from other photographers. <br/>Be sure to upload a photo with your question. </div>
    <div class="question_form">
    <%= form_tag({ :action => :create, :controller => :questions }, :multipart => true) do %>
      <div><%= text_field_tag :title, nil, placeholder: "Enter question", :class => "question_field" %></div>

      <div><%= file_field_tag :file, accept: 'image/png,image/gif,image/jpeg', :class => "choose_button" %>
</div>

      <div><%= text_area_tag :content, nil , rows: 4 , cols: 45, placeholder: 'Add additional description here.', :class => "question_field" %>
        <div><%= submit_tag("Submit Question") %></div>
      </div>
    <% end %>
    </div>

</div>

app/views/questions/show.html.erb
<div class="section group">
  <div class="col span_2_of_4">

  <div class="single_question">
      <span class="single_title">
      <h2><%= @question.title %> </h2>
      <h4>Asked by: <%= @question.user.username %></h4>
    </span>
  </div>
</div>

<div class="col span_2_of_4">
  <div class="answer-form-header">
        <h3>Answers</h3>
  </div>
</div>

</div>

<div class="section group">    
  <div class="col span_4_of_6">
    <table>
      <tr>
        <td class="question-vote" id='voting-panel'>
          <%= render partial: 'shared/voting', locals: { votable: @question } %>
        </td>
        <td class="single_photo_upload">
          <p><img src="<%= @question.path || @question.file%>"></p>
        </td>
      </tr>
      <tr>
        <td class="question-vote"></td>
        <td class="description">
          <p><%= @question.content %></p>
        </td>
      </tr>
      <tr>
        <td class="question-vote"></td>
        <td class="comment_on_question">
           <% @question.comments.each do |comment| %>
             <%= render partial: 'comments/comment', locals: { comment: comment } %>
           <% end %>
           <p><%= render partial: 'comments/new', locals: { commentable: @question } %></p>
        </td>
      </tr>
    </table>
  </div>
  
<div class="col span_2_of_6">
  <div class="question_answers">
    <% @question.answers.each do |answer| %>
       <%= render partial: 'answers/show', locals: { answer: answer } %>
    <% end %>
  </div>
   <%= render "answers/new" %>
</div>
</div>
   
</div>

app/views/shared/_navbar.html.erb
<!-- <nav> -->
  <% if @current_user %>
    <%= link_to @current_user.username, user_path(@current_user) %>
    <%= link_to "(Logout)", logout_path %>
  <% else %>
   <%= link_to "Signup", signup_path %> | 
   <%= link_to "Login", login_path %>
  <% end %> 
<!-- </nav> -->

<i class="icon-user"></i> 

app/views/shared/_navbar_logout.html.erb
<!-- <nav> -->
  <% if @current_user %>
    
    <%= link_to logout_path do %>
    <i class="icon-off"></i><br /><span class="nav-text">Log out</span>
    <% end %>
   <% else %>
   <%= link_to login_path do %>
   <i class="icon-key"></i><br /><span class="nav-text">Log in</span>
   <% end %>
  <% end %> 
<!-- </nav> -->

app/views/shared/_navbar_username.html.erb
<!-- <nav> -->
  <% if @current_user %>
    <%= link_to user_path(@current_user) do %>
    <i class="icon-user"></i><br />
    <span class="nav-text"><%= @current_user.username %></span>
    <% end %>
  <% else %>
   <%= link_to signup_path  do %>
   <i class="icon-user"></i><br /> <span class="nav-text">Sign Up</span>
   <% end %>
  <% end %> 
<!-- </nav> -->

app/views/shared/_voting.html.erb
<%= link_to votes_path(votable_id: votable.id, votable_type: votable.class, direction: 1), method: :post, :class => "vote" do %>
  <i class="icon-chevron-sign-up"></i>
<% end %>

<span id="vote-count"><%= votable.votes_count %></span>

<%= link_to votes_path(votable_id: votable.id, votable_type: votable.class, direction: 0), method: :post, :class => "vote" do %>
  <i class="icon-chevron-sign-down"></i>
<% end %>

app/views/users/_comment.html.erb
<div>
  <span>
    <%= link_to question.title, question_path(question.id) %>
  </span></div>
  <div class="photo_upload">
  <img src="<%= question.path || question.file.thumb %>">
</div>

app/views/users/_myanswer.html.erb
<div class="first_line_all_questions">
  <span class="title">
    <%= link_to myanswer.content, question_path(myanswer.question) %>
  </span></div>

app/views/users/_subnav.html.erb
<!-- <div class="subnavbar_user_profile">
  < link_to "Summary", user_path(@current_user), class: "link_user_nav" %>
  < link_to "My Questions", profile_questions_path, class: "link_user_nav" >
  < link_to "My Answers", profile_answers_path, class: "link_user_nav" >
  < link_to "Edit", root_path, class: "link_user_nav" %>
</div>
 -->

app/views/users/_userstats.html.erb
<table>
<tr>
  <td>Username: </td>
  <td><%= @current_user.username %></td>
</tr>
<tr>
  <td>Questions: </td>
  <td><%= @current_user.questions.count %></td>
</tr>
<tr>
  <td>Answers: </td>
  <td><%= @current_user.answers.count %></td>
</tr>
<tr>
  <td>Comments: </td>
  <td><%= @current_user.comments.count %></td>
</tr>
</table>

app/views/users/answers.html.erb
<%= stylesheet_link_tag "user_profile" %>
<div class="main_content">
<h1> Account Page </h1>
<h2> Questions of <%= @current_user.username%> </h2>

<%= render partial: "subnav"%>

<% if @questions %>
  <%= render @questions.reverse %>
<% else %>
  <p> You have not yet asked a question </p>
<% end %>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <p><%= user %></p>
<% end %>

app/views/users/new.html.erb
<div class="user_creation">
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :username, placeholder: 'username' %>
  <%= f.text_field :email, placeholder: 'email' %>
  <%= f.password_field :password, placeholder: 'password' %>
  <%= f.submit "Create" %>

<% end %>
</div>

app/views/users/profile_answers.html.erb
<%= stylesheet_link_tag "user_profile" %>
<div class="main_content">
<h1> Account Page </h1>
<h2> Answers of <%= @current_user.username%> </h2>
<%= render partial: "subnav"%>

<% if @answers %>
  <%= render :partial => "myanswer", :collection => @answers.reverse.shift(5) %>
<% else %>
  <p> You have not yet asked a question </p>
  <!-- Link to ask a question now -->
<% end %>
</div>

app/views/users/profile_edit.html.erb
<div class="user_creation">
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :username, placeholder: 'username' %>
  <%= f.text_field :email, placeholder: 'email' %>
  <%= f.password_field :password, placeholder: 'password' %>
  <%= f.submit %>

<% end %>
</div>

app/views/users/profile_questions.html.erb
<%= stylesheet_link_tag "user_profile" %>
<div class="main_content">
<h1> Account Page </h1>
<h2> Questions of <%= @current_user.username%> </h2>
<%= render partial: "subnav"%>

<% if @questions %>
  <%= render @questions.reverse %>
<% else %>
  <p> You have not yet asked a question </p>
<% end %>
</div>

app/views/users/show.html.erb
<div class="main_content">
<h1> Account Page </h1>
<h2> Summary for <%= @current_user.username%> </h2>

<%= render partial: "subnav"%>
<%= render partial: "userstats"%>


<p> My Latest 5 Questions </p>
<hr>
<% if @questions %>
  <%= render @questions.reverse.shift(5) %>
<% else %>
  <p> You have not yet asked a question </p>
<% end %>

<hr>
<p> My Latest 5 Answers </p>
<hr>
<% if @myanswers %>
  <%= render :partial => "myanswer", :collection => @myanswers.reverse.shift(5) %>
<% else %>
  <p> You have not yet asked a question </p>
  <!-- Link to ask a question now -->
<% end %>
</div>